config/routes.rb
Electrodynamics::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :only => [:index, :show] do
    get 'personal', :on => :member
  end
  resources :themes, :only => [:show]
  resources :organizations
  resources :comments
  resources :blogs
  resources :documents
  resources :invites
  resources :articles do 
    collection do
      get 'by_category'
      get 'by_organizations'
    end
  end
  match '/news' => 'articles#news', as: :news
  match '/search' => 'static_pages#search', as: :search
  root :to => 'static_pages#index'
  ActiveAdmin.routes(self)
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :text, :title, :tag_ids
  
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :comments
  
  belongs_to :author, class_name: 'User'
  belongs_to :category
end

app/models/article_tag.rb
class ArticleTag < ActiveRecord::Base
  attr_accessible :article_id, :tag_id
  
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  
  has_many :articles
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :country_id, :name
  belongs_to :country
  default_scope order('cities.name ASC')
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :comment, :author_id, :document_id
  
  belongs_to :author, class_name: 'User'
  belongs_to :article
  belongs_to :document
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  has_many :cities
  scope :with_cities, includes(:cities).where("cities.country_id != 0")
  default_scope order('countries.name ASC')
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :text, :title, :image, :file
  has_many :comments
  has_attached_file :image, :styles => { :thumb => "309x309#" }
  has_attached_file :file
  do_not_validate_attachment_file_type :file
  has_many :document_tags
  has_many :tags, through: :document_tags
end

app/models/document_tag.rb
class DocumentTag < ActiveRecord::Base
  attr_accessible :document_id, :tag_id
  
  belongs_to :document
  belongs_to :tag
end

app/models/employe.rb
class Employe < ActiveRecord::Base
  attr_accessible :firstname, :lastname, :organization_id, :position
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :email, :token
  
  has_many :user_invites
  has_many :users, through: :user_invites
  
  validates :email, :uniqueness => true
end

app/models/notice_configuration.rb
class NoticeConfiguration < ActiveRecord::Base
  attr_accessible :to_mailbox, :to_personal_messages, 
                  :about_new_messages, :about_my_comment_reply, :about_my_reply_comments, :about_mention_me, :about_new_subscriber
  belongs_to :user
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :index, :title, :establish_date, :site, :address, :employees, :about
  
  has_many :users
  has_many :employees
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :title
  
  has_many :article_tags
  has_many :articles, through: :article_tags
  has_many :document_tags
  has_many :articles, through: :document_tags
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  attr_accessible :title
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :current_password, :token
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, 
                  :role, :nickname, :current_password, :country_id, :city_id, :notice_configuration_attributes, :organization_id, :token
                  
  has_one :notice_configuration
  belongs_to :organization
  accepts_nested_attributes_for :notice_configuration, allow_destroy: true
  
  has_many :user_invites
  has_many :invites, through: :user_invites
  
  validates :firstname, :lastname, :nickname, :role, :presence => true
  validates :token, :presence => true, :on => :create
  validate :validates_token_is_correct, :on => :create
  
  ROLES = %w[admin moderator user]
  
  def admin?
    self.role == "admin" 
  end
  
  def validates_token_is_correct
    invite = Invite.find_by_email(self.email)
    errors.add(:token, I18n.t("token_is_incorrect")) unless
    invite && invite.token == self.token
  end
    

  def first_name_with_last_name
      "#{firstname} #{lastname}" if firstname && lastname
  end
  
  def invite_qty
    if self.role == "admin" 
      I18n.t('infinite_qty')
    else
      5 - self.invites.count
    end
  end
  
  def has_invites
    self.invites.count < 5 || self.role == "admin" 
  end
end

app/models/user_invite.rb
class UserInvite < ActiveRecord::Base
  attr_accessible :invite_id, :user_id
  
  belongs_to :user
  belongs_to :invite
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
  
  before_filter :all_articles, :only => [:index, :news, :by_category, :by_organizations]
  
  def index 
  end
  
  def news
    @articles = Article.all
    @mine = Article.where(:author_id => current_user.id) if user_signed_in?
  end
  
  def by_category
  end
  
  def by_organizations
  end
  
  def show 
    @article = Article.find(params[:id])
    @comment = Comment.new
    @articles = Article.includes(:tags).where(:tags => {:id => @article.tags})
  end
  
  def all_articles
    case true
    when params[:category].present?
      @articles = Article.where(:category_id => params[:category])
    when params[:tag].present?
      @articles = Article.includes(:tags).where(:tags => {:id => params[:tag]})
    else
      @articles = Article.all
    end
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
  def index 
    @articles = Article.all
    @mine = Article.where(:author_id => current_user.id) if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!, only: [:personal]
  
  def index
    @articles = Article.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def personal
    current_user.build_notice_configuration unless current_user.notice_configuration
    @invite = Invite.new
  end
end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper
  
  def controller?(*controller)
     controller.include?(params[:controller])
   end

   def action?(*action)
     action.include?(params[:action])
   end
  
  def date_with_month(date)
    I18n.localize(date, :format => :with_month)
  end
  
  def date_without_time(date)
    I18n.localize(date, :format => :without_time)
  end
  
  def link_to_delete_comment(user, comment)
    link_to 'удалить', comment_path(comment), :method => :delete, :confirm => 'Вы уверены?' if comment.author_id == user.id
  end
  
  def users
    User.where('firstname != ?', 'admin')
  end
  
  def categories_list
    Category.all
  end
  
  def side_articles
    Article.limit(5)
  end
  
  def random_article
    Article.all.sample
  end
  
  def countries
    Country.all
  end
  
  def cities
    Citi.all
  end
  
  def tags
    Tag.all
  end
  
  def organization_title(user)
    # if user.organization && Organization.exists?(user.organization) && user.organization.title
      user.organization.title
    # end
  end
  
  def country(object)
    if object && Country.exists?(object)
      country = Country.find(object)
      country.try(:name)
    end
  end
  
  def city(object)
    if object && City.exists?(object)
      country = City.find(object)
      country.try(:name)
    end
  end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.slim
.article
  span = article.created_at.strftime('%d.%m.%y %H:%M') 
  span = ', автор '
  = link_to article.author.first_name_with_last_name, user_path(article.author) if article.author
  h1 = article.title
  span тэги: 
  - article.tags.each do |tag|
    = (link_to tag.title, articles_path(:tag => tag.id)) + ' '
  .article_text
    = truncate(article.text, length: 1300)
  = link_to 'Читать далее', article, :class => 'btn btn-primary'

app/views/articles/_form.slim
= simple_form_for @article do |f|
  .form-group
    = f.input :title, label: 'Заголовок', input_html: { class: 'form-control' }
    = f.input :text, label: 'Текст', input_html: { class: 'form-control', rows: 7 }
    = f.association :tags,
      collection: Tag.all.map{ |t| [t.title, t.id] },
      include_blank: true, 
      input_html: { class: 'chosen-select', :data => {:placeholder => 'Выберите теги '} }, 
      label: 'Теги'
    = f.submit "Создать", :class => "btn btn-primary"

app/views/articles/_tabs.slim
.nav.nav-tabs.nav-justified
  = content_tag(:li, (link_to 'Лучшие', articles_path), :class => (action?('index') ? 'active' : nil ))
  = content_tag(:li, (link_to 'По категории', by_category_articles_path), :class => (action?('by_category') ? 'active' : nil ))
  = content_tag(:li, (link_to 'Организации', by_organizations_articles_path), :class => (action?('by_organizations') ? 'active' : nil ))

app/views/articles/by_category.slim
.row
  .col-md-9
    .nav.nav-tabs.nav-justified
    = render 'tabs'
    = render @articles
  .col-md-3
    = render 'shared/categories'

app/views/articles/by_organizations.slim
.row
  .col-md-9
    .nav.nav-tabs.nav-justified
    = render 'tabs'
    = render @articles
  .col-md-3
    = render 'shared/articles', :heading => 'Что обсуждают', :@articles => side_articles

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.slim
.row
  .col-md-9
    .nav.nav-tabs.nav-justified
      = content_tag(:li, (link_to 'Лучшие'), :class => 'active')
      = content_tag(:li, (link_to 'По категории'))
      = content_tag(:li, (link_to 'Организации'))
    = render @articles
  .col-md-3
    = render 'shared/articles', :heading => 'Что обсуждают', :@articles => side_articles
    = render 'shared/categories'

app/views/articles/new.slim
.row
  .col-md-9
    = render 'form'
    
  .col-md-3
    = render 'shared/right_panel'

app/views/articles/news.slim
.row
  .col-md-9
    ul.nav.nav-tabs.nav-justified
      = content_tag(:li, (link_to 'Моя подборка', '#mine', :data => { :toggle => 'tab' }), :class => 'active')
      = content_tag(:li, (link_to 'Все новости', '#all', :data => { :toggle => 'tab' }))
    .tab-content
      .tab-pane.active id="mine"
        - if user_signed_in?
          = render @mine
        - else
          br
          br
          h5 Вы не авторизованы в системе
      .tab-pane id="all"
          = render @articles
  .col-md-3
    = link_to 'Настроить ленту новостей', '#', :class => 'btn btn-primary', :id => 'configure_news_list' 
    = render 'shared/articles', :heading => 'Лучшие', :@articles => side_articles

app/views/articles/show.slim
.row
  .col-md-9
    span = @article.created_at.strftime('%d.%m.%y %H:%M') 
    span = ', автор '
    = link_to @article.author.first_name_with_last_name, user_path(@article.author) if @article.author
    h1 = @article.title
    span тэги: 
    - @article.tags.each do |tag|
      = (link_to tag.title, '#') + ' '
    .article_text
      = @article.text
    ul.media-list
    h3 Комментарии (#{@article.comments.count})
    - @article.comments.each do |comment|
      .media
        a.pull-left href="#"
          img.media-object src="/assets/64.svg" alt="..."
        .media-body
          h4.media-heading #{link_to comment.author.first_name_with_last_name, "#"}, #{date_with_month(comment.created_at)} #{link_to_delete_comment(current_user, comment) if user_signed_in? }
          = comment.comment
    - if user_signed_in?
      h3 Оставить свой комментарий
      = form_for @comment do |f|
        = f.text_area :comment, class: 'form-control', rows: 3
        = f.hidden_field :author_id, :value => (current_user.id if current_user)
        = f.hidden_field :article_id, :value => @article.id 
        = f.submit "Отправить", :class => "btn btn-primary"
  .col-md-3
    = render 'shared/articles', :heading => 'Похожие статьи'