config/routes.rb
Electrodynamics::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :only => [:index, :show] do
    get 'personal', :on => :member
  end
  resources :themes, :only => [:show]
  resources :organizations
  resources :comments
  resources :blogs
  resources :documents
  resources :invites
  resources :articles do 
    collection do
      get 'by_category'
      get 'by_organizations'
    end
  end
  match '/news' => 'articles#news', as: :news
  match '/search' => 'static_pages#search', as: :search
  root :to => 'static_pages#index'
  ActiveAdmin.routes(self)
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :text, :title, :tag_ids
  
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :comments
  
  belongs_to :author, class_name: 'User'
  belongs_to :category
end

app/models/article_tag.rb
class ArticleTag < ActiveRecord::Base
  attr_accessible :article_id, :tag_id
  
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  
  has_many :articles
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :country_id, :name
  belongs_to :country
  default_scope order('cities.name ASC')
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :comment, :author_id, :document_id
  
  belongs_to :author, class_name: 'User'
  belongs_to :article
  belongs_to :document
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  has_many :cities
  scope :with_cities, includes(:cities).where("cities.country_id != 0")
  default_scope order('countries.name ASC')
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :text, :title, :image, :file
  has_many :comments
  has_attached_file :image, :styles => { :thumb => "309x309#" }
  has_attached_file :file
  do_not_validate_attachment_file_type :file
  has_many :document_tags
  has_many :tags, through: :document_tags
end

app/models/document_tag.rb
class DocumentTag < ActiveRecord::Base
  attr_accessible :document_id, :tag_id
  
  belongs_to :document
  belongs_to :tag
end

app/models/employe.rb
class Employe < ActiveRecord::Base
  attr_accessible :firstname, :lastname, :organization_id, :position
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :email, :token
  
  has_many :user_invites
  has_many :users, through: :user_invites
  
  validates :email, :uniqueness => true
end

app/models/notice_configuration.rb
class NoticeConfiguration < ActiveRecord::Base
  attr_accessible :to_mailbox, :to_personal_messages, 
                  :about_new_messages, :about_my_comment_reply, :about_my_reply_comments, :about_mention_me, :about_new_subscriber
  belongs_to :user
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :index, :title, :establish_date, :site, :address, :employees, :about
  
  has_many :users
  has_many :employees
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :title
  
  has_many :article_tags
  has_many :articles, through: :article_tags
  has_many :document_tags
  has_many :articles, through: :document_tags
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  attr_accessible :title
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :current_password, :token
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, 
                  :role, :nickname, :current_password, :country_id, :city_id, :notice_configuration_attributes, :organization_id, :token
                  
  has_one :notice_configuration
  belongs_to :organization
  accepts_nested_attributes_for :notice_configuration, allow_destroy: true
  
  has_many :user_invites
  has_many :invites, through: :user_invites
  
  validates :firstname, :lastname, :nickname, :role, :presence => true
  validates :token, :presence => true, :on => :create
  validate :validates_token_is_correct, :on => :create
  
  ROLES = %w[admin moderator user]
  
  def admin?
    self.role == "admin" 
  end
  
  def validates_token_is_correct
    invite = Invite.find_by_email(self.email)
    errors.add(:token, I18n.t("token_is_incorrect")) unless
    invite && invite.token == self.token
  end
    

  def first_name_with_last_name
      "#{firstname} #{lastname}" if firstname && lastname
  end
  
  def invite_qty
    if self.role == "admin" 
      I18n.t('infinite_qty')
    else
      5 - self.invites.count
    end
  end
  
  def has_invites
    self.invites.count < 5 || self.role == "admin" 
  end
end

app/models/user_invite.rb
class UserInvite < ActiveRecord::Base
  attr_accessible :invite_id, :user_id
  
  belongs_to :user
  belongs_to :invite
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
  def index 
    @articles = Article.all
    @mine = Article.where(:author_id => current_user.id) if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!, only: [:personal]
  
  def index
    @articles = Article.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def personal
    current_user.build_notice_configuration unless current_user.notice_configuration
    @invite = Invite.new
  end
end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper
  
  def controller?(*controller)
     controller.include?(params[:controller])
   end

   def action?(*action)
     action.include?(params[:action])
   end
  
  def date_with_month(date)
    I18n.localize(date, :format => :with_month)
  end
  
  def date_without_time(date)
    I18n.localize(date, :format => :without_time)
  end
  
  def link_to_delete_comment(user, comment)
    link_to 'удалить', comment_path(comment), :method => :delete, :confirm => 'Вы уверены?' if comment.author_id == user.id
  end
  
  def users
    User.where('firstname != ?', 'admin')
  end
  
  def categories_list
    Category.all
  end
  
  def side_articles
    Article.limit(5)
  end
  
  def random_article
    Article.all.sample
  end
  
  def countries
    Country.all
  end
  
  def cities
    Citi.all
  end
  
  def tags
    Tag.all
  end
  
  def organization_title(user)
    # if user.organization && Organization.exists?(user.organization) && user.organization.title
      user.organization.title
    # end
  end
  
  def country(object)
    if object && Country.exists?(object)
      country = Country.find(object)
      country.try(:name)
    end
  end
  
  def city(object)
    if object && City.exists?(object)
      country = City.find(object)
      country.try(:name)
    end
  end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_articles.slim
h1 Статьи
.row
  .col-md-12
    table.table.users_table
      thead
        td Название
        td collspan=2 Категория 
      tbody
        - Article.all.each do |article|
          tr
            td 
              h5 = link_to article.title, article
            td 
              = %w[статьи блог].sample
            td 
              = link_to "Переназначить категорию", "#"

app/views/users/_contacts.slim
h1 Контакты
.row
  .col-md-3
    .checkbox
      label
        = check_box_tag :my_subscribers
        |подписаны на меня
  .col-md-3
    .checkbox
      label
        = check_box_tag :to_whom_i_subscribed
        |я подписан на них
= render '/shared/users_table'

app/views/users/_invites.slim
.row
  .col-xs-4
    h1 Инвайты
    - if current_user.has_invites
      p Доступное количество инвайтов – #{current_user.invite_qty}
      = form_for @invite do |f|
        = f.text_field :email, class: 'form-control', :placeholder => 'email'
        br
        = f.submit "Отправить", :class => "btn btn-primary"
    -else
      p У вас не осталось инвайтов

app/views/users/_messages.slim
h1 Сообщения

app/views/users/_personal.slim
= form_for(current_user, :url => registration_path(current_user), :html => { :method => :put }) do |f|
  .row
    .col-md-6
        .row
          .col-xs-8
            h1 Профиль
            = f.text_field :firstname, class: 'form-control', :placeholder => 'Имя'
            = f.text_field :lastname, class: 'form-control', :placeholder => 'Фамилия'
            = f.text_field :nickname, class: 'form-control', :placeholder => 'Никнейм'
            h1 Местоположение
        .row
          .col-xs-4
            = f.collection_select :country_id, Country.order(:name), :id, :name, {prompt: 'Страна'}, {:class => 'form-control'}
          .col-xs-4
             = f.grouped_collection_select :city_id, Country.order(:name), :cities, :name, :id, :name, {prompt: 'Выберите город'}, {:class => 'form-control'}
        h1 Тип пользователя
        .row
         .col-xs-10
           = f.select(:role, User::ROLES.map {|r| [ t(r), r]}, {:prompt => 'Выберите тип пользователя'}, { :class => 'form-control' })
           .role_description
    .col-md-6
      = f.fields_for :notice_configuration do |n|
        h1 Уведомления
        .checkbox
          label
            = n.check_box :to_mailbox 
            |На почтовый ящик
        .checkbox
          label
            = n.check_box :to_personal_messages 
            |В личные сообщения
        h1 Отправлять мне уведомления
        .checkbox
          label
            = n.check_box :about_new_messages 
            |о новых сообщениях
        .checkbox
          label
            = n.check_box :about_my_comment_reply 
            |о новых ответах на мои комментарии
        .checkbox
          label
            = n.check_box :about_my_reply_comments 
            |о новых комментариях к моим ответам      
        .checkbox
          label
            = n.check_box :about_mention_me 
            |при упоминании меня в постах, вопросах или комментариях          
        .checkbox
          label
            = n.check_box :about_new_subscriber 
            |при добавлении нового подписчика
  .row
    .col-md-12
      = f.submit "Сохранить", :class => "btn btn-success "

app/views/users/_subscriptions.slim
h1 Подписки

app/views/users/_users.slim
h1 Пользователи
.row
  .col-md-12
    table.table.users_table
      thead
        td Имя
        td Email
        td Роль
        td
        td
        td
      tbody
        - User.all.each do |user|
          tr
            td 
              h5 = link_to user.first_name_with_last_name, user
            td 
              = user.email
            td 
              #{link_to "Одобрить", "#"} / #{link_to "Отклонить", "#"}
            td 
              #{link_to "Сменить роль", "#"}
            td 
              #{link_to "Заблокировать", "#"}

app/views/users/index.slim
= render '/shared/users_table'

app/views/users/personal.slim
.row
  .col-md-9
    ul.nav.nav-tabs
      = content_tag(:li, (link_to 'Личные', '#personal', :data => { :toggle => 'tab' }), :class => 'active')
      = content_tag(:li, (link_to 'Подписки', '#subscriptions', :data => { :toggle => 'tab' }))
      = content_tag(:li, (link_to 'Мои контакты', '#contacts', :data => { :toggle => 'tab' }))
      = content_tag(:li, (link_to 'Мои сообщения', '#messages', :data => { :toggle => 'tab' }))
      = content_tag(:li, (link_to 'Инвайты', '#invites', :data => { :toggle => 'tab' }))
      - if current_user.admin?
        = content_tag(:li, (link_to 'Пользователи', '#users', :data => { :toggle => 'tab' }))
        = content_tag(:li, (link_to 'Статьи', '#articles', :data => { :toggle => 'tab' }))

.tab-content
  .tab-pane.active id="personal"
    = render 'personal'
  .tab-pane id="subscriptions"
    = render 'subscriptions'
  .tab-pane id="contacts"
    = render 'contacts'
  .tab-pane id="messages"
    = render 'messages'
  .tab-pane id="invites"
    = render 'invites'
  - if current_user.admin?
    .tab-pane id="users"
      = render 'users'
    .tab-pane id="articles"
      = render 'articles'

app/views/users/show.slim
.row.user_profile
  .col-md-1
    = image_tag('/assets/user_pic.jpg')
  .col-md-8
    - if user_signed_in? && request.fullpath != user_path(current_user)
      .pull-right
        = link_to 'Подписаться', '#', :class => 'btn btn-primary'
    h2 = @user.first_name_with_last_name
    h5 Ведущий инженер электромагнитных аномалий в #{link_to "Роскосмос"}
    h3 276-й в рейтинге
    h4 Дата рождения: 2 декабря 1980
    h4 Откуда: Россия, Москва и Московская обл., Москва
    h4 Никнейм: #{@user.nickname.present? ? @user.nickname : "не указан"}
    h4 Область интересов: #{link_to "Закон Джоуля-Ленца"}, #{link_to "Трансформаторы"}, #{link_to "Потенциал"}
    h4 О себе: 
    p Работаю на должности регионального менеджера по продажам LSI в России и СНГ. С 2000 года начал работать Системным Администратором в крупной торговой компании, с 2004 года занимаюсь системами хранения данных (СХД). Профессиональные интересы включают в себя системное администрирование, HA-кластеризацию, HPC, СХД, Серверное железо, виртуализация, построение крупных Веб-ДЦ.
    h4 Подписан на статьи из разделов:  #{link_to "Проектирование"}, #{link_to "Монтаж"}, #{link_to "Радиоантенны"}
    h4 Работает в организациях: #{link_to "Роскосмос"}, #{link_to "Centrobit"}
    h3 Контакты недоступны.
    p Пользователь ограничил доступ к контактной информации, она видна только списку контактов пользователя Александр Зейников
    - if user_signed_in? && request.fullpath != user_path(current_user)
      = link_to '+ Добавить в свои контакты', '#', :class => 'btn btn-primary'
      .pull-right
        = link_to 'Написать личное сообщение', '#', :class => 'btn btn-primary'
  .col-md-3
    .jumbotron
      h4 Активность пользователя
      = link_to "3 статьи"
      br
      = link_to "28 комментариев"
      br
      = link_to "14 контактов (10 коллег)"
      br
      = link_to "40 документов загружено"
    