config/routes.rb
Electrodynamics::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :only => [:index, :show] do
    get 'personal', :on => :member
  end
  resources :themes, :only => [:show]
  resources :organizations
  resources :comments
  resources :blogs
  resources :documents
  resources :invites
  resources :articles do 
    collection do
      get 'by_category'
      get 'by_organizations'
    end
  end
  match '/news' => 'articles#news', as: :news
  match '/search' => 'static_pages#search', as: :search
  root :to => 'static_pages#index'
  ActiveAdmin.routes(self)
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :text, :title, :tag_ids
  
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :comments
  
  belongs_to :author, class_name: 'User'
  belongs_to :category
end

app/models/article_tag.rb
class ArticleTag < ActiveRecord::Base
  attr_accessible :article_id, :tag_id
  
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
  
  has_many :articles
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :country_id, :name
  belongs_to :country
  default_scope order('cities.name ASC')
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :comment, :author_id, :document_id
  
  belongs_to :author, class_name: 'User'
  belongs_to :article
  belongs_to :document
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
  has_many :cities
  scope :with_cities, includes(:cities).where("cities.country_id != 0")
  default_scope order('countries.name ASC')
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :text, :title, :image, :file
  has_many :comments
  has_attached_file :image, :styles => { :thumb => "309x309#" }
  has_attached_file :file
  do_not_validate_attachment_file_type :file
  has_many :document_tags
  has_many :tags, through: :document_tags
end

app/models/document_tag.rb
class DocumentTag < ActiveRecord::Base
  attr_accessible :document_id, :tag_id
  
  belongs_to :document
  belongs_to :tag
end

app/models/employe.rb
class Employe < ActiveRecord::Base
  attr_accessible :firstname, :lastname, :organization_id, :position
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :email, :token
  
  has_many :user_invites
  has_many :users, through: :user_invites
  
  validates :email, :uniqueness => true
end

app/models/notice_configuration.rb
class NoticeConfiguration < ActiveRecord::Base
  attr_accessible :to_mailbox, :to_personal_messages, 
                  :about_new_messages, :about_my_comment_reply, :about_my_reply_comments, :about_mention_me, :about_new_subscriber
  belongs_to :user
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :index, :title, :establish_date, :site, :address, :employees, :about
  
  has_many :users
  has_many :employees
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :title
  
  has_many :article_tags
  has_many :articles, through: :article_tags
  has_many :document_tags
  has_many :articles, through: :document_tags
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  attr_accessible :title
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :current_password, :token
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, 
                  :role, :nickname, :current_password, :country_id, :city_id, :notice_configuration_attributes, :organization_id, :token
                  
  has_one :notice_configuration
  belongs_to :organization
  accepts_nested_attributes_for :notice_configuration, allow_destroy: true
  
  has_many :user_invites
  has_many :invites, through: :user_invites
  
  validates :firstname, :lastname, :nickname, :role, :presence => true
  validates :token, :presence => true, :on => :create
  validate :validates_token_is_correct, :on => :create
  
  ROLES = %w[admin moderator user]
  
  def admin?
    self.role == "admin" 
  end
  
  def validates_token_is_correct
    invite = Invite.find_by_email(self.email)
    errors.add(:token, I18n.t("token_is_incorrect")) unless
    invite && invite.token == self.token
  end
    

  def first_name_with_last_name
      "#{firstname} #{lastname}" if firstname && lastname
  end
  
  def invite_qty
    if self.role == "admin" 
      I18n.t('infinite_qty')
    else
      5 - self.invites.count
    end
  end
  
  def has_invites
    self.invites.count < 5 || self.role == "admin" 
  end
end

app/models/user_invite.rb
class UserInvite < ActiveRecord::Base
  attr_accessible :invite_id, :user_id
  
  belongs_to :user
  belongs_to :invite
end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper
  
  def controller?(*controller)
     controller.include?(params[:controller])
   end

   def action?(*action)
     action.include?(params[:action])
   end
  
  def date_with_month(date)
    I18n.localize(date, :format => :with_month)
  end
  
  def date_without_time(date)
    I18n.localize(date, :format => :without_time)
  end
  
  def link_to_delete_comment(user, comment)
    link_to 'удалить', comment_path(comment), :method => :delete, :confirm => 'Вы уверены?' if comment.author_id == user.id
  end
  
  def users
    User.where('firstname != ?', 'admin')
  end
  
  def categories_list
    Category.all
  end
  
  def side_articles
    Article.limit(5)
  end
  
  def random_article
    Article.all.sample
  end
  
  def countries
    Country.all
  end
  
  def cities
    Citi.all
  end
  
  def tags
    Tag.all
  end
  
  def organization_title(user)
    # if user.organization && Organization.exists?(user.organization) && user.organization.title
      user.organization.title
    # end
  end
  
  def country(object)
    if object && Country.exists?(object)
      country = Country.find(object)
      country.try(:name)
    end
  end
  
  def city(object)
    if object && City.exists?(object)
      country = City.find(object)
      country.try(:name)
    end
  end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger">
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.slim
doctype
html
  head
    title Electrodynamics
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  body
    .container
      = render 'shared/top_menu'
      - if notice
        div.alert.alert-info
          = notice
      - if alert
        div.alert.alert-danger
          = alert
      = yield

app/views/shared/_articles.slim
.jumbotron
  h4 = heading
  - @articles.each do |article|
    = link_to article.title, article
    .similar_article_date = article.created_at.strftime('%d.%m.%y') 
    

app/views/shared/_categories.slim
.jumbotron
  h4 Категории
  - categories_list.each do |category|
    h5 = link_to category.title, by_category_articles_path(:category => category.id)

app/views/shared/_right_panel.slim
.jumbotron
  | Векторное поле притягивает предел функции, что несомненно приведет нас к истине. Замкнутое множество уравновешивает косвенный интеграл от функции, обращающейся в бесконечность в изолированной точке, что и требовалось доказать. Точка перегиба отображает экстремум функции, таким образом сбылась мечта идиота - утверждение полностью доказано. Аффинное преобразование, как следует из вышесказанного, допускает изоморфный определитель системы линейных уравнений, дальнейшие выкладки оставим студентам в качестве несложной домашней работы. Замкнутое множество решительно изменяет Наибольший Общий Делитель (НОД), как и предполагалось.
  | Вектор, следовательно, существенно нейтрализует линейно зависимый криволинейный интеграл, что несомненно приведет нас к истине. Теорема стремится к нулю. Рациональное число последовательно. Дифференциальное уравнение, как следует из вышесказанного, позитивно позиционирует стремящийся максимум, как и предполагалось.
  | Умножение вектора на число последовательно. Тем не менее, огибающая транслирует косвенный разрыв функции, при этом, вместо 13 можно взять любую другую константу. Эпсилон окрестность неоднозначна. Определитель системы линейных уравнений, очевидно, нормально распределен.

app/views/shared/_similar_articles.slim
.jumbotron
  h4 Похожие статьи
  - @articles.each do |article|
    = link_to article.title, article
    .similar_article_date = article.created_at.strftime('%d.%m.%y') 
    

app/views/shared/_tags.slim
.jumbotron
  h4 Искать по тэгам
  = select_tag "tags", options_from_collection_for_select(Tag.all, :id, :title), multiple: true, :class => 'chosen-mini', :data => {:placeholder => 'Выберите тэг', :width => '200px'}
  br
  br
  

app/views/shared/_top_menu.slim
.topmenu
  .row
    .col-md-4.logo 
      = link_to root_path do
        h4 Electrodynamics.ru
    .col-md-5
      form.form-inline
        .form-group
          input.form-control placeholder="Умный поиск по сайту"
        = link_to 'Искать', search_path, :class => 'btn btn-primary with_left_indent'
        
    .col-md-3
      ul.nav.nav-pills
        - if user_signed_in? 
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" = current_user.first_name_with_last_name
              span.caret
            ul.dropdown-menu
              li = link_to 'личный кабинет', personal_user_path(current_user)
              li = link_to 'моя страница', user_path(current_user)
              li = link_to 'выйти', destroy_user_session_path
        - else 
          li = link_to 'войти', new_user_session_path
          li = link_to ' зарегистрироваться', new_user_registration_path          
  .row
    .col-md-12
      ul.nav.nav-pills.nav-justified
        = content_tag(:li, (link_to 'Новости', news_path), :class => ('active' if action?('news')))
        = content_tag(:li, (link_to 'Записи', articles_path), :class => ('active' if controller?('articles') && action?('index')))
        = content_tag(:li, (link_to 'Библиотека', documents_path), :class => ('active' if controller?('documents')))
        = content_tag(:li, (link_to 'Организации', organizations_path), :class => ('active' if controller?('organizations')))
        = content_tag(:li, (link_to 'Пользователи', users_path), :class => ('active' if controller?('users') && action?('index')))
        = content_tag(:li, (link_to 'Блоги', blogs_path), :class => ('active' if controller?('blogs')))
      
    

app/views/shared/_tree.html.erb
<div class="jumbotron">
    <div>
        <ul class="nav nav-list">
            <li><label class="tree-toggler nav-header">+ Образование</label>
                <ul class="nav nav-list tree">
                    <li><a href="#">Проектирование</a></li>
                    <li><a href="#">Монтаж</a></li>
                    <li><a href="#">Радиоантенны</a></li>
                    <li><label class="tree-toggler nav-header">+ Производство</label>
                        <ul class="nav nav-list tree">
                            <li><a href="#">Проектирование</a></li>
                            <li><a href="#">Монтаж</a></li>
                            <li><a href="#">Радиоантенны</a></li>
                            <li><label class="tree-toggler nav-header">+ Наука</label>
                                <ul class="nav nav-list tree">
                                    <li><a href="#">Радиоэлектроника</a></li>
                                    <li><a href="#">Видеокассеты</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="divider"></li>
            <li><label class="tree-toggler nav-header">+ Видео с учеными</label>
                <ul class="nav nav-list tree">
                    <li><a href="#">Разрешенное</a></li>
                    <li><a href="#">Запретное</a></li>
                    <li><label class="tree-toggler nav-header">+ На грани фантастики</label>
                        <ul class="nav nav-list tree">
                            <li><a href="#">Сферы</a></li>
                            <li><a href="#">Лучи</a></li>
                        </ul>
                    </li>
                    <li><label class="tree-toggler nav-header">+ В поисках истины</label>
                        <ul class="nav nav-list tree">
                            <li><a href="#">Прошлое</a></li>
                            <li><a href="#">Секретные знания</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

app/views/shared/_users_table.slim
.row
  .col-md-12
    table.table.users_table
      thead
        td
        td Организация
        td Рейтинг
      tbody
        - users.each do |user|
          tr
            td 
              h3 = link_to user.first_name_with_last_name, user
            td 
              = user.organization_id ? (link_to organization_title(user), organization_path(user.organization.id)) : nil
            td 
              = user.id